### ISSUE TITLE
Define method of "Registering for NYCCamp 2014" (and promote that method.)

### ISSUE THREAD

**Issue by jonpugh** [NYC-Camp/website#73] opened 2014-03-01 17:02 UTC
I think there is still confusion about how exactly to say we are coming to NYCCamp 2014.

There has a been a lot of debate about OG, what type of event nodes to use, etc.

What if we took the approach Drupal.org uses and added checkboxes to the profile field for all the events a user attended, plans to attend? I think this would greatly simplify things for users as all they would have to do is edit their account profile (and we could have the checkbox on the user/register page.)

Thoughts?

**Comment by ForestMars** [comment] 2014-03-01 17:06
Yep, big +1 for easy to understand checkboxes on the user's profile. The should be prompted to make those selections when they register for this year's camp. 

As for the implementation, there should be little if any 'debate' about what nodes to use, as it's clearly defined- event node type for all, er, events, and a single node of type conference for 2014 camp attendance. 

Is there still confusion there, or does that make sense?

**Comment by likewhoa** [comment] 2014-03-02 18:49
What you suggest might just be suggest we remove og functionality since that's what cod depends on with event types since those are turned into organic groups, am I right?

**Comment by ForestMars** [comment] 2014-03-02 19:47
@jonpugh Initial thoughts: 
1. How does the event coordinator message everyone interested in / attending the event? Currently this is done with OG.
2. I don't think the alternative you describe (profile checkboxes) simplifies things for users, in so far as last year it was exceedingly simple for users- indeed, they just checked off boxes when they registered for the site, and done. 
3. Somewhere along the way, someone has borked that extremely simply setup. 
4. What does need to be simplified is our development / communication process, I think. I'm seeing a lot of noise and apparent misunderstanding.

**Comment by jonpugh** [comment] 2014-03-04 05:30
There are no checkboxes on user/register or user/%/edit at all.  

If those return for NYCCamp 2014 then this is closed.

**Comment by ForestMars** [comment] 2014-03-04 14:12
> "There are no checkboxes on user/register or user/%/edit at all."

Right, that's not really the problem, that's just a setting in OG. 

The problem is that someone started changing all of last year's event nodes to be this year's. Ugh, that is such an anti-pattern. (Did you ever have a client that just created one node for their front page stories, and just changed its content? Ouch.) 

So if we turn on reg right now, users will actually be registering for last year's events, some of which now have different descriptions. So frankly, it's a bit of a mess. 

What needs to happen though is simple, we just need to add all the events for this year. This is going to take someone an hour or 2 to do, I surmise. 

ps. not sure why you closed this? If I'm missing something here, please LMK.

**Comment by mirie** [comment] 2014-03-04 14:34
@ForestMars, please see: #90. Also please see: #64 re: event nodes.

**Comment by mirie** [comment] 2014-03-05 01:27
I am closing this because this now becoming a duplicate of other referenced tickets and @ForestMars went ahead and created new nodes for all of the events.

**Closed as completed by mirie** 2014-03-05 01:27 UTC
Labels: question
