### ISSUE TITLE
Featured Attendees

### ISSUE THREAD

**Issue by willykaram** [NYC-Camp/website#92] opened 2014-03-05 02:59 UTC
One feature of which we are in somewhat desperate/immediate need is the ability to promote featured attendees on the homepage of the NYC Camp site. This would appear in a block on the homepage beneath the main header, and would need to involve either a slideshow or preferably a carousel:

**Comment by mirie** [comment] 2014-03-05 03:05
duplicate of #93. Closing.

**Closed as completed by mirie** 2014-03-05 03:05 UTC
