### ISSUE TITLE
Anonymous users issue (bug in COD) 

### ISSUE THREAD

**Issue by mirie** [NYC-Camp/website#36] opened 2014-02-25 02:18 UTC
An anonymous user has access to particular content types on: http://nyccamp.org/node/add/
    • Room
    • Schedule Item
    • Session
    • Time Slot
If an anonymous user clicks on: http://nyccamp.org/node/add/session, that user gets redirected to:http://nyccamp.org/session/propose/lightning. This node add form also displays the Revision information.

This is related to the OG permissions/access controls.

**Comment by ForestMars** [comment] 2014-02-25 02:25
On the website call tonight we agreed to punt on this for now, since it is a bug in COD, and not a regression we introduced.

**Comment by ForestMars** [comment] 2014-02-25 02:35
@esod Can you add a link to the upstream issue please?

**Comment by ForestMars** [comment] 2014-02-25 07:49
Having just resolved https://github.com/NYC-Camp/website/issues/38 we can now open up sessions; however we still have the apparently OG related bug that is allowing anon users to create types of content at http://nyccamp.org/node/add/room, /node/add/time-slot & node/add/schedule, which roughly correspond to the bundles that have OG field settings defined: 

http://www.nyccamp.org/admin/config/group/fields

**Comment by ForestMars** [comment] 2014-02-25 16:18
@Sergey-Semashko - Can you take a look at this?

**Comment by mirie** [comment] 2014-02-26 01:21
From Skype chat, Willy wrote:

From what I can see in the various core and OG permissions tables, all the node grants and field perms are the same bet 2013 and 2014 (at least for the time slot entity I'm looking at). That would lead me to think that is a core role/perms issue or OG group/perms issue, a not an entity/fields perms issue. 

It's happening across multiple entities w/different field, and deleting the relevant OG field doesn't impact the issue. Which makes me thinks that the role/group perms is the cause and that it applies to any entities/field which are being governed by OG/the group.

We have entities setup as OG "Group content" which allows them to be referenced in OG entities, and in turn OG is thus managing these permissions (which we don't have set correctly). 

To resolve the issue, I suggest that we simply remove this OG functionality/field on these entities since we're not using either aspect of this OG functionality (we're only using registration entities to handle registration for events/sessions, not the OG groups). If for some reason we still want people to be able express interest in an event/session, then instead of using OG, I suggest that we simply use a simple entity reference to due so (there's less overhead and permissions complications). At a minimum, we should also be certain to strip back the OG perms, and leave these handled by Drupal Core as there would be nothing relating to our Group were we would need to have group specific permissions/access controls (if kept in place, we want the groups as open as possible).  As a result, we essentially would not be using any of the OG functionality. If necessary, in due course this would let us potentially completely uninstall and remove OG and related modules in due course once we address any other dependencies; but I don't think this is necessary right now to solve our immediate issues for this year's camp. 

If we don't want to go this route, the we need to go into the OG UI and adjust the both the bundle/field permissions for the relevant OG Group roles in order to resolve the problem we're encountering, since they override the other permissions/modules were using. But as mentioned above, that likely doesn't make sense given we're not using this OG functionality, which was geared to deal w/year over year issues and other broader conference functionality. Additionally, I think some debate is still (for obvious reasons) ongoing about the merits of this OG approach. If for some reason, this debate concludes in favor of OG, we can reimplement this pretty easily on the NYC Camp site

**Comment by mirie** [comment] 2014-02-26 01:28
I agree with this idea: 

> we simply remove this OG functionality/field on these entities since we're not using either aspect of this OG functionality

**Comment by ForestMars** [comment] 2014-02-26 01:36
I can't agree with that at this point. We didn't have this issue last year; ergo it's either a bug in cod or something we messed up. In case 1 we need to work with upstream to fix, in case 2 we need to undo what we messed up. 

We can always just add a rule to prevent anon users from accessing those pages.

**Comment by mirie** [comment] 2014-02-26 16:57
Adding link for @esod 's upstream issue: https://drupal.org/node/2205773

**Comment by mirie** [comment] 2014-02-28 00:57
@esod, 

I'm updating this issue to include what we discussed last night:

We decided to disable the OG functionality until after the camp when we'll have more time to investigate the problem. 

This means removing those OG field settings, correct? --> /admin/config/group/fields

**Comment by ForestMars** [comment] 2014-02-28 01:42
I am very much again disabling cod until there is a discussion here and the reasons are clearly stated.

**Comment by ForestMars** [comment] 2014-02-28 01:45
This issue in particular, #36, relates to a putative bug in COD, however one that is not a showstopper, given there are workarounds such as using Rules.

If additional complications were discussed they need to be documented here, or a new issue crested to track the problem.

**Comment by likewhoa** [comment] 2014-03-03 17:08
referencing #83 for those that don't know as this issue relates and should be closed once that gets merged into live

**Comment by likewhoa** [comment] 2014-03-03 18:58
Closing this. feels good man

**Closed as completed by likewhoa** 2014-03-03 18:58 UTC
Labels: bug
